{
 "title": "Page Analytics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Realtime Events",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "page_analytics",
     "rawSql": "SELECT event_type, event_count FROM fact_events_realtime_agg \r\nWHERE start_time = (SELECT MAX(start_time) FROM fact_events_realtime_agg)"
    }
   ]
  },
  {
   "title": "Sources/Referrals",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "page_analytics",
     "rawSql": "SELECT source, count(1) source_count\r\nFROM fact_events \r\nWHERE $__timeFilter(timestamp AT TIME ZONE 'IST')\r\nGROUP BY source"
    }
   ]
  },
  {
   "title": "Average Page Load time / Hour",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "page_analytics",
     "rawSql": "WITH events AS (\r\n    SELECT hour, page_load_time_ms\r\n    FROM fact_events\r\n    JOIN dim_time\r\n    ON fact_events.time_key = dim_time.time_key\r\n    WHERE $__timeFilter(timestamp AT TIME ZONE 'IST') \r\n)\r\nSELECT \r\n    COALESCE(AVG(page_load_time_ms), 0) as page_load_time,\r\n    CONCAT(h.hour_of_day, '-', h.hour_of_day+1) as hour_of_day\r\nFROM \r\n    GENERATE_SERIES(0, 23) AS h(hour_of_day)\r\n    LEFT JOIN events\r\n    ON events.hour = h.hour_of_day\r\nGROUP BY\r\n    h.hour_of_day\r\nORDER BY\r\n    h.hour_of_day"
    }
   ]
  }
 ]
}