
CREATE TABLE IF NOT EXISTS "dim_time" (
	"time_key" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"seconds" INTEGER NOT NULL,
	"minute" INTEGER NOT NULL,
	"hour" INTEGER NOT NULL,
	PRIMARY KEY("time_key")
);




CREATE TABLE IF NOT EXISTS "dim_date" (
	"date_key" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"year" INTEGER NOT NULL,
	"month" INTEGER NOT NULL,
	"day" INTEGER NOT NULL,
	"week_number" INTEGER NOT NULL,
	"day_of_week" INTEGER NOT NULL,
	"day_name_of_week" VARCHAR(255) NOT NULL,
	"day_of_year" INTEGER NOT NULL,
	PRIMARY KEY("date_key")
);




CREATE TABLE IF NOT EXISTS "dim_locations" (
	"location_key" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"country_name" VARCHAR(255) NOT NULL,
	"latitude" VARCHAR(255) NOT NULL,
	"longitude" VARCHAR(255) NOT NULL,
	PRIMARY KEY("location_key")
);




CREATE TABLE IF NOT EXISTS "dim_users" (
	"user_key" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_name" VARCHAR(255),
	PRIMARY KEY("user_key")
);


CREATE TABLE IF NOT EXISTS "fact_events" (
	"event_key" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"date_key" BIGINT NOT NULL,
	"time_key" INTEGER NOT NULL,
	"location_key" INTEGER NOT NULL,
	"user_key" INTEGER NOT NULL,
	"timestamp" TIMESTAMP NOT NULL,
	"source" VARCHAR(255) NOT NULL,
	"event_type" VARCHAR(255) NOT NULL,
	"page_url" VARCHAR(255) NOT NULL,
	"product_category" VARCHAR(255) NOT NULL,
	"page_load_time_ms" INTEGER NOT NULL,
	PRIMARY KEY("event_key")
);


CREATE TABLE IF NOT EXISTS "fact_events_realtime_agg" (
	"event_agg_key" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"start_time" TIMESTAMP NOT NULL,
	"end_time" TIMESTAMP NOT NULL,
	"event_type" VARCHAR(255) NOT NULL,
	"event_count" INTEGER NOT NULL,
	PRIMARY KEY("event_agg_key")
);


ALTER TABLE "fact_events"
ADD FOREIGN KEY("date_key") REFERENCES "dim_date"("date_key")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_events"
ADD FOREIGN KEY("time_key") REFERENCES "dim_time"("time_key")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_events"
ADD FOREIGN KEY("location_key") REFERENCES "dim_locations"("location_key")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_events"
ADD FOREIGN KEY("user_key") REFERENCES "dim_users"("user_key")
ON UPDATE NO ACTION ON DELETE NO ACTION;